### ISSUE TITLE
pressure field not stored in influxdb

### ISSUE THREAD

**Issue by sillevl** [vives-projectwerk-2-2020/lorawan-listener#1]
Only `temperature`, `humidity`, `pm10` and `pm2.5` are stored, but `pressure` values are not.

https://github.com/vives-projectwerk-2-2020/lorawan-listener/blob/c7a16147cd927d060f2ed9cc2ff6d6e6561ca840/src/app.js#L30

**Comment by ArnoWillems** [comment]
Pressure is now added.
