### ISSUE TITLE
`location` should not be added into influxdb

### ISSUE THREAD

**Issue by sillevl** [vives-projectwerk-2-2020/lorawan-listener#4]
https://github.com/vives-projectwerk-2-2020/lorawan-listener/blob/c7a16147cd927d060f2ed9cc2ff6d6e6561ca840/src/app.js#L28

`location` data (and all other metadata) is stored into the MySQL database and not the InfluxDB. 
Please remove.

**Comment by ArnoWillems** [comment]
Location is no longer in data.
